exe 'source' stdpath('config').'/general/settings.vim'
exe 'source' stdpath('config').'/general/haskell.vim'
exe 'source' stdpath('config').'/keys/mappings.vim'
exe 'source' stdpath('config').'/vim-plug/plugins.vim'
exe 'source' stdpath('config').'/plug-config/coc.vim'
exe 'source' stdpath('config').'/plug-config/nerdtree.vim'
exe 'source' stdpath('config').'/plug-config/fugitive.vim'
exe 'source' stdpath('config').'/general/last.vim'
